### ISSUE TITLE
No image in `Deploy all functions` step of walkthrough

### ISSUE THREAD

**Issue by bamurtaugh** [Azure/azure-functions-vscode-web#12]
This is what I see:

![Image](https://github.com/user-attachments/assets/da366f05-eefa-4683-a110-41c086fab545)

**Comment by EvanR-Dev** [comment]
Discussed offline but - to summarize:
We do not have an image/gif for that step - when you create and run for the first time, the function code will be on right half of the editor. We can consider adding something there as the user may close that tab
