### ISSUE TITLE
Seeking more guidance when deploying

### ISSUE THREAD

**Issue by bamurtaugh** [Azure/azure-functions-vscode-web#13]
I selected `Deploy all` from the getting started walkthrough and got this warning:

![Image](https://github.com/user-attachments/assets/0e676a50-3af4-4615-81c8-17dd127af454)

As someone newer to Functions, I'm not sure if I should be concerned about this. Could there be a `Learn more` link in this blocking modal, and perhaps also in the walkthrough step too?

**Comment by EvanR-Dev** [comment]
Learn more added
