### ISSUE TITLE
Unclear `Save project code` getting started step

### ISSUE THREAD

**Issue by bamurtaugh** [Azure/azure-functions-vscode-web#14]
There's no image, and nothing happened when I clicked `Save`:

![Image](https://github.com/user-attachments/assets/6f703ccb-7211-47ee-b776-972f90566f4a)

**Comment by EvanR-Dev** [comment]
Discussed offline but - to summarize:
We do not have an image/gif for that step - when you create and run for the first time, the function code will be on right half of the editor. We can consider adding something there as the user may close that tab

Related to #12

**Comment by EvanR-Dev** [comment]
Added image of GH and Download button location. Same for Deploy all (Azure Portal deployed copy example image)
