### ISSUE TITLE
[Bug]: Portal error message when creating a new Flex Consumption App

### ISSUE THREAD

**Issue by nirmash** [Azure/azure-functions-vscode-web#15]
### Function app name

https://llt1.azurewebsites.net

### Expected Behavior *

Limelight button visible

### Actual Behavior *

Error message appears "We were not able to load some functions in the list due to errors. Refresh the page to try again. See details"

### Steps to Reproduce

Create a new Flex Consumption App in EastUS 
Wait for Overview blade to appear 
Note: Error message goes away when clicking the refresh button

### Environment

MacOS Sonoma 14.6.1

### Priority

High (not-working at all)

**Comment by EvanR-Dev** [comment]
I believe this is unrelated to Limelight - something to do with sync triggers that is a transient error we've seen before

**Comment by EvanR-Dev** [comment]
Closing in favor of #25
