### ISSUE TITLE
[Bug]: When I click on the Run/Test it runs the function app with the selected function but the enumerated functions under the Run/Test go away when the function completes

### ISSUE THREAD

**Issue by eamonoreilly** [Azure/azure-functions-vscode-web#16]
### Function app name

N/A

### Expected Behavior *

The Run/Test should keep the enumerated functions available after the function runs so that you can execute the specific function again as needed. Currently, when the function finishes, the functions listed under Run/Test disappear so you can't test the function or any other functions again. When you click on Run / Test again, you get the below error about list functions in the workspace.

![image](https://github.com/user-attachments/assets/0d7a63a9-e59a-46b4-94ae-267a8dae82d6)
![image](https://github.com/user-attachments/assets/dcdfd56c-8295-4e70-ade1-978a85ee4368)

### Actual Behavior *

Error listing functions as shown above in expected behavior.

### Steps to Reproduce

1) Create a http function.
2) Click Run/Test to start the function app and then select the http function.
3) When the function completes, the http function disappears from the Run/Test section.
4) If you click on Run/Test again, it fails to enumerate the functions so you can't select from the selection bar

### Priority

High (not-working at all)

**Comment by EvanR-Dev** [comment]
Addressed but will keep this open for testing

**Comment by EvanR-Dev** [comment]
I see the issue - using the wrapper extension locally does work, but using it in the LL environment does not. This is likely with the way the debugger is still attached after executing for the first time. Addressing further

**Comment by EvanR-Dev** [comment]
Fixed in newest release - in vscode.dev, Core Tools stays alive after debugging is stopped
