### ISSUE TITLE
[Bug]: Save button on Welcome Page doesn't do anything

### ISSUE THREAD

**Issue by nirmash** [Azure/azure-functions-vscode-web#17]
### Function app name

https://llt2.azurewebsites.net

### Expected Behavior *

Some kind of action should take place, the text we have now is not telling customers how to proceed from there. 

### Actual Behavior *

Clicked the Save button and nothing happened

### Steps to Reproduce

Create a new function
Click the "Create in VS Code for Web"
Go through the steps in the Welcome page 
Click save button

### Priority

Low (happening rarely)

**Comment by EvanR-Dev** [comment]
Thanks - fixed and released

**Comment by nirmash** [comment]
what was the fix? I suggest opening the Source Control pane?

**Comment by nirmash** [comment]
never mind found it, looks good!
