### ISSUE TITLE
Unexpected empty state upon reconnection

### ISSUE THREAD

**Issue by bamurtaugh** [Azure/azure-functions-vscode-web#18]
I let my session go idle for a few hours, so then I needed to reconnect.

Upon reconnecting, my project is gone. I suppose this is expected since it's somewhat of an ephemeral session, but I would've loved to get a warning early on (maybe in the getting started walkthrough)? Is there any way to block this loss of connection and loss of data?

Additionally, it's a bit confusing that I'm still brought to the end of the getting started walkthrough, even though I have no project code to save anymore.

![Image](https://github.com/user-attachments/assets/b7663d46-efb9-4d40-9517-1a1361a1f59f)

**Comment by EvanR-Dev** [comment]
Unfortunately there isn't a way for VS Code to programatically reset walkthroughs. This is tracked here: https://github.com/microsoft/vscode/issues/212819
