### ISSUE TITLE
Want more guidance for picking a function

### ISSUE THREAD

**Issue by bamurtaugh** [Azure/azure-functions-vscode-web#20]
As I `Create a project` from the getting started walkthrough, I'm prompted to pick a language and then my project's first function. I'd love guidance on which to pick:

![Image](https://github.com/user-attachments/assets/8735dfcf-6ae7-41de-b6da-669d97137a44)

Could there be a link to docs in the walkthrough to help me learn more? And/or links to docs within the quick pick itself? We do this in the `Add Dev Container Configuration Files` flow in the Dev Containers extension:

![Image](https://github.com/user-attachments/assets/ed800c11-346e-48e2-8bd2-93ac8e899051)

**Comment by EvanR-Dev** [comment]
This selection is provided by the normal Az Fx ext. In the walkthough, there are now Learn More links to give more context for users that would like to know more about these and the creation of functions
