### ISSUE TITLE
[Bug]: When opening an existing function, VS prompts overwriting the "func: host start" in tasks.json

### ISSUE THREAD

**Issue by nirmash** [Azure/azure-functions-vscode-web#22]
### Function app name

https://llt2.azurewebsites.net

### Expected Behavior *

Since Function was already deployed properly, a dialog box that breaks debugging should not show up. Basically, nothing should happen. ### 

### Actual Behavior *

A dialog box shows up saying: "This will overwrite the following tasks in your tasks.json: "func: host start"". Options are "Cancel" and "Overwrite". If Overwrite is selected, local debugging breaks as the function host doesn't know how to start.

### Steps to Reproduce

Create Flex Consumption Function App
Create a new function with Limelight 
Close the VS Code tab 
Re-launch Limelight from Portal
Dialog will show up

### Priority

Low (happening rarely)

**Comment by EvanR-Dev** [comment]
Looking into this - we try to initialize the workspace for the user behind the scenes. This accidentally seems to prompt the user when refreshing - working on a fix

**Comment by EvanR-Dev** [comment]
Closed in favor of #39
