### ISSUE TITLE
Unclear if I should use various Azure status bar entries

### ISSUE THREAD

**Issue by bamurtaugh** [Azure/azure-functions-vscode-web#24]
I noticed 3 different entries in the status bar related to Azure services:

![Image](https://github.com/user-attachments/assets/dd3f3cf7-0372-4fc4-a0a9-47fce7119fe8)

I tried clicking on each of them, and I got notifications various things started and stopped, but I'm not sure if I'm meant to click these, if they're useful, or what these services are doing when I click them.

If they aren't helpful for users in this Functions flow, could we hide these entry points? If they are potentially helpful, I wonder if we could add some docs/guidance somewhere?

**Comment by YunchuWang** [comment]
Hi @bamurtaugh, thanks for pointing out. these service are from azurite extension are auto started/stopped when user executes azure function in the limelight session and use azurite for function runtime metadata storage https://learn.microsoft.com/en-us/azure/azure-functions/functions-develop-local. i will take a look to help make this more intuitive to user.

**Comment by YunchuWang** [comment]
Took a look and i would suggest adding this as a step in get started flow in wrapper extension to provide contextual details on azurite function usage. Reassigning to @EvanR-Dev

**Comment by EvanR-Dev** [comment]
We don't want to expose to many details to the user. The walkthrough now includes some "Learn More" links to our docs to clarify this (the run/test section)

Also will be adding an intro page that contains details about a session (max timeout, azurite usage, etc) - similar to VS Code's release notes tab on launch
