### ISSUE TITLE
[Bug]: Portal showing up with error for an empty app

### ISSUE THREAD

**Issue by vrdmr** [Azure/azure-functions-vscode-web#25]
### Function app name

vrdmr-powershell74-2048-aue-1
vrdmr-python310-2048-eas-1

### Expected Behavior *

Should show the empty app page with all the editing options.
![image](https://github.com/user-attachments/assets/5b467aae-6de8-472f-bbef-1bffaf9cd457)

### Actual Behavior *

<img width="1001" alt="image" src="https://github.com/user-attachments/assets/03aec8d5-42b6-46fb-85f3-a267fd87d5f5">

<img width="710" alt="image" src="https://github.com/user-attachments/assets/cd55bc95-8f22-4639-b25c-d93c820bf96a">

### Steps to Reproduce

Using my personal subscription for this.

### Environment

Production - non Microsoft Tenant

### Screenshots

Added

### Priority

Hight (happening consistently)

**Comment by EvanR-Dev** [comment]
Sync triggers issue - this is being looked at by the platform team actively. To be fixed in 104 release
