### ISSUE TITLE
Unable to create a function using the VSCode command palette.

### ISSUE THREAD

**Issue by pdthummar** [Azure/azure-functions-vscode-web#26]
### Function app name

LMbugbashNode20

### Expected Behavior *

It should create a function.

### Actual Behavior *

Command palette disappears

### Steps to Reproduce

1. Created new FC app
2. opened it in vscode web
3. Go to Command palette
4. Command palette disappears

### Priority

Low (happening rarely)

**Comment by EvanR-Dev** [comment]
@pdthummar could you attach a repo video/image?

**Comment by EvanR-Dev** [comment]
The cause was from the extensions view being switched to - resolved
