### ISSUE TITLE
We should enable -Xfronzen_modules=off when running locally

### ISSUE THREAD

**Issue by eamonoreilly** [Azure/azure-functions-vscode-web#27]
### Feature Name *

Enable local debugging

### Feature Description *

I currently see this warning on Python 3.11 around debugging locally.

[2024-08-16T16:42:02.911Z] 0.00s - Debugger warning: It seems that frozen modules are being used, which may
[2024-08-16T16:42:02.911Z] 0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off

I have observed that the debugger only hits a breakpoint once and then fails to hit it for subsequent runs of the function.

### Benefits

Can debug a function successfully during development.

### Alternatives

Have to restart the function app for each time a function is run in order to hit the breakpoint

**Comment by EvanR-Dev** [comment]
Seems like a debugpy issue

**Comment by EvanR-Dev** [comment]
Adding "PYDEVD_DISABLE_FILE_VALIDATION": "1" to local.settings.json silences the warning - does not affect debugging. Will be added to Python apps

**Comment by EvanR-Dev** [comment]
Reopening just for temporary visibility for the bugbash - to be released. Can be fixed manually by adding "PYDEVD_DISABLE_FILE_VALIDATION": "1" to local.settings.json

Not having this does not affect debugging

**Comment by EvanR-Dev** [comment]
Released
