### ISSUE TITLE
[Bug]: Deploy All button enabled when there's no project

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-functions-vscode-web#28]
### Function app name

glengatest-flex-py

### Expected Behavior *

The **Deploy All** button should be disabled until after you create a project.
<img width="707" alt="image" src="https://github.com/user-attachments/assets/c9e767e7-2b05-4e18-8f43-90ba6ca0a635">

### Actual Behavior *

I clicked the **Deploy All** button before **Create** and the Preparing message just spins (obviously) instead of saying "Create an app first, dummy"

### Suggested Fix

Disable Deploy All until after Create

### Priority

Medium (intermittent)

**Comment by EvanR-Dev** [comment]
Closing in favor of #34
