### ISSUE TITLE
[Bug]: editor keeps returning to extensions tab

### ISSUE THREAD

**Issue by hallvictoria** [Azure/azure-functions-vscode-web#29]
### Expected Behavior *

When clicking the files tab, the editor should keep that tab open.

### Actual Behavior *

When clicking the files tab, the editor would keep returning to the extensions tab after a few seconds.

### Steps to Reproduce

1. (Unsure if it had any effect, but I had a session open with one app)
2. Create and deploy a Python HTTP trigger flex app.
3. Open the app in VSCode
4. Firstly, no welcome page showed up.
5. Try to click on the files tab.
6. Wait a few seconds, and the tab will switch back to the extension tab
[Video 8-16 at 11.48.webm](https://github.com/user-attachments/assets/01b136c2-7b04-4466-968c-71685cc0e4ee)

### Priority

Low (happening rarely)

**Comment by EvanR-Dev** [comment]
This only happens when one of the extensions fails to install properly - there is an infinite loop to get back to this view. Our agent has all exts installed by default now. This is a better approach as the image size increase did not affect coldstart as much as the exts being installed dynamically
