### ISSUE TITLE
[Bug]: Image in walkthroughs should load

### ISSUE THREAD

**Issue by TylerLeonhardt** [Azure/azure-functions-vscode-web#32]
### Expected Behavior *

image in walkthrough loads

### Actual Behavior *

<img width="1679" alt="image" src="https://github.com/user-attachments/assets/e1c7b0e7-3154-48dc-b342-8eb3b2978f93">

### Environment

Safari macOS 

### Priority

Low (happening rarely)

**Comment by EvanR-Dev** [comment]
Hey @TylerLeonhardt 
I'm having issues reproducing this as I tried with a newly created Node 20 FC app:
![image](https://github.com/user-attachments/assets/835f226e-7d71-4c85-9e08-eaad9819951e)

Was this an undeployed or deployed app? And when did you open the walkthrough at this point (before or after creation if this was not a deployed app)?

**Comment by TylerLeonhardt** [comment]
<img width="1679" alt="image" src="https://github.com/user-attachments/assets/5cecda79-9777-43af-8610-260928af8b6e">
Still repros. 

Safari Version 17.6 (19618.3.11.11.5)

**Comment by EvanR-Dev** [comment]
Interesting - going to test with different devices and browsers here to see what's happening

**Comment by EvanR-Dev** [comment]
There was an issue with Mac users - replaced markdowns with direct images and gifs. Confirmed on Mac these show up now
