### ISSUE TITLE
[Bug]: Create in Create a project also adds new triggers

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-functions-vscode-web#33]
### Function app name

glengatest-flex-py

### Expected Behavior *

After I create my project, **Create** should instead say "Add a trigger"
If we can't do that, the text should explain that **Create** also adds a new trigger to the project.

### Priority

Low (happening rarely)

**Comment by EvanR-Dev** [comment]
Proposing to change the tree view - linked to #45

**Comment by EvanR-Dev** [comment]
Changed tree view - reflected
