### ISSUE TITLE
Warn or block users from trying to save empty project

### ISSUE THREAD

**Issue by bamurtaugh** [Azure/azure-functions-vscode-web#34]
I don't think I should be able to initiate the `Save project code` flow in a blank project. I complete these steps:

![Image](https://github.com/user-attachments/assets/4df621b1-9eb4-421d-b5ea-d6370273002d)

![Image](https://github.com/user-attachments/assets/372bce33-1847-4326-9b47-05be223c3e68)

But nothing happens because I don't have any code (I just connected to new compute after a timeout, so my previous project is gone).

**Comment by EvanR-Dev** [comment]
There are now warnings for when trying to save or deploy an empty project
