### ISSUE TITLE
[Bug]: Powershell experience not working

### ISSUE THREAD

**Issue by vrdmr** [Azure/azure-functions-vscode-web#35]
### Actual Behavior *

<img width="573" alt="image" src="https://github.com/user-attachments/assets/efe3aa03-3199-49a3-b47b-c2bd8592a0f6">

<img width="575" alt="image" src="https://github.com/user-attachments/assets/cc97e092-48a6-4d0e-8792-d41eaf5e005e">

### Steps to Reproduce

When clicking the "Create Project" button - it did create files but then threw these error messages.

### Priority

Low (happening rarely)

**Comment by EvanR-Dev** [comment]
Powershell worker 7.2 is targeted by Core tools - needed .NET6 SDK. Released
