### ISSUE TITLE
[Bug]: Deploy tries and fails to deploy to the wrong app

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-functions-vscode-web#36]
### Function app name

glengatest-flex-py

### Expected Behavior *

When I select **Deploy all** my project gets deployed to my function app (glengatest-flex-py).

### Actual Behavior *

I get this error:
<img width="341" alt="image" src="https://github.com/user-attachments/assets/5169ca1c-2bc4-4a04-9938-8979adc274d8">
and the app resource indicated is the wrong app 😦 

### Priority

High (not-working at all)

**Comment by EvanR-Dev** [comment]
Fixed and released in latest ext version
