### ISSUE TITLE
[Bug]: PowerShell core tools not working

### ISSUE THREAD

**Issue by vrdmr** [Azure/azure-functions-vscode-web#37]
### Function app name

vrdmr-powershell74-2048-eus-1

### Actual Behavior *

<img width="628" alt="image" src="https://github.com/user-attachments/assets/d0e07dcd-430f-4566-8881-81710a1da6e9">

### Priority

Low (happening rarely)

**Comment by EvanR-Dev** [comment]
To be updated with a new image using our new EV2 CI

**Comment by EvanR-Dev** [comment]
Closing in favor of #35
