### ISSUE TITLE
How can I get back to the getting started walkthrough?

### ISSUE THREAD

**Issue by bamurtaugh** [Azure/azure-functions-vscode-web#38]
I switched to insiders.vscode.dev from vscode.dev, and I don't see the getting started walkthrough. I wanted the guidance, so I went to search for the walkthrough, but I don't see it in the list.

I thought all extension walkthroughs would appear through the `Welcome: Open Walkthrough...` command, but I don't see any related to Functions:

![Image](https://github.com/user-attachments/assets/8da6548c-c1c9-485d-aeb5-4f6ec2919107)

**Comment by EvanR-Dev** [comment]
You should be able to open the walkthrough via Command Palette


![Image](https://github.com/user-attachments/assets/92664647-4a99-497e-adbc-c0c60cf07729)

**Comment by bamurtaugh** [comment]
cc @bhavyaus as I think you were taking a closer look at the behavior / appearance of this walkthrough?

**Comment by EvanR-Dev** [comment]
Walkthrough can be found specifically under the walkthroughs of VS Code (not a separate cmd)
