### ISSUE TITLE
[Bug]: Page refresh causes a warning (which maybe isn't needed)

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-functions-vscode-web#39]
### Function app name

glengatest-flex-py

### Expected Behavior *

Page reloads without errors/warnings.

### Actual Behavior *

A vague warning is displayed, which probably isn't even needed.
<img width="395" alt="image" src="https://github.com/user-attachments/assets/62ae68f1-861d-4e92-b31d-764251d47fb1">

### Steps to Reproduce

1. Create the project in VSCode Web.
1. Try to publish (which failed, see my previous bug)
1. Refresh the site (as recommended)

### Priority

Low (happening rarely)

**Comment by EvanR-Dev** [comment]
Fixed and released
