### ISSUE TITLE
[Bug]: Empty Node Add doesn't show the workspace view

### ISSUE THREAD

**Issue by vrdmr** [Azure/azure-functions-vscode-web#40]
### Expected Behavior *

It should show the view to create apps.

### Actual Behavior *

<img width="380" alt="image" src="https://github.com/user-attachments/assets/21711e5a-beb2-455d-b3df-a6c8d5213be2">

Once I Created the project - 
<img width="381" alt="image" src="https://github.com/user-attachments/assets/a08a2767-0d1a-4d1c-869c-7c46e48f32c3">

### Priority

Low (happening rarely)

**Comment by EvanR-Dev** [comment]
Let's keep this in mind - unable to reproduce. But the tree view has also changed from our discussion with the vscode.dev team
