### ISSUE TITLE
[Bug]: Functions Extension should generate .gitignore and local.settings.json files for existing projects initialization.

### ISSUE THREAD

**Issue by vrdmr** [Azure/azure-functions-vscode-web#42]
### Actual Behavior *

New project does generate - local.settings.json and .gitignore
![image](https://github.com/user-attachments/assets/2e6f96b3-f3d2-4b31-9c64-862d182dc21a)

Initialize project does not generate - local.settings.json and .gitignore
![image](https://github.com/user-attachments/assets/09723fcb-073a-44fd-a503-e849b46026f5)
![image](https://github.com/user-attachments/assets/e092c502-8fb3-4ca4-88fd-2d0875d14723)

### Priority

Low (happening rarely)

**Comment by YunchuWang** [comment]
https://azfunc.visualstudio.com/AzFunc-DevSessions/_git/AzFunc-DevSessions-VSCodeExt/commit/eac93e410931bba7eabc287521b9f48a8774356b?refName=refs%2Fheads%2Fdev released
