### ISSUE TITLE
[Bug]: New project must include a .gitignore file to prevent publishing local.settings.json

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-functions-vscode-web#43]
### Function app name

glengatest-flex-py

### Expected Behavior *

New project should be created with a .gitignore file (but not a .git folder).

### Actual Behavior *

Without a .gitignore file, you are asked to "select which files should be included in the repository"

**CUSTOMERS ARE GOING TO PUBLISH EVERTHING SELECTED INCLUDING THE LOCAL.SETTINGS.JSON FILE**

### Steps to Reproduce

1. Create a new project in VSCode 4 Web
2. select the source control tab
3. select **Publish to GitHub**
4. Choose your target GitHub account.

### Priority

Medium (intermittent)

**Comment by EvanR-Dev** [comment]
Closing in favor of #42
