### ISSUE TITLE
[Bug]: download instructions don't lead to successful download

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-functions-vscode-web#44]
### Function app name

glengatest-flex-py

### Expected Behavior *

<img width="508" alt="image" src="https://github.com/user-attachments/assets/e369716e-d233-4c6a-b38d-452a55859215">  

This helps me download my files

### Actual Behavior *

<img width="508" alt="image" src="https://github.com/user-attachments/assets/20f9c7f2-4634-4d9a-aa22-08230dcee717">  

I couldn't follow these to get a download option.

### Steps to Reproduce

1. Create a project
2. Click Save > Download

### Priority

Medium (intermittent)

**Comment by EvanR-Dev** [comment]
Closing in favor of #47 - tracking there
