### ISSUE TITLE
[Feature]: Rethink "toolbar"

### ISSUE THREAD

**Issue by TylerLeonhardt** [Azure/azure-functions-vscode-web#45]
### Feature Name *

Rethink Toolbar

### Feature Description *

<img width="461" alt="image" src="https://github.com/user-attachments/assets/50f9eaec-7288-43b1-87cc-cdbb074f7473">

The "toolbar" in a tree view feels very out of place and [goes against VS Code best practices](https://code.visualstudio.com/api/ux-guidelines/views). I understand that it's supposed to be one place for all your Functions actions, but it feels very out of place and is another view for the user to manage.

Instead I think these actions should be either:
* Left to where they are typically in VS Code (in other words, not "all in one place")
* Use something more transient, like the Command Palette, to display all actions

The actions you want are:
* Create a function
* Run/Test app
* Deploy app
* Save app
* Feedback

Couple ideas:

> First off, [review our UX guidelines](https://code.visualstudio.com/api/ux-guidelines/overview), we put a lot of effort into them!

* Use [Context Menus](https://code.visualstudio.com/api/ux-guidelines/context-menus) to show actions where relevant
  * I could see in the Explorer context menu, Create Function, Deploy App, Save App
* Leverage the [Command Palette](https://code.visualstudio.com/api/ux-guidelines/command-palette) to show common actions (`vscode.commands.executeCommand('workbench.action.quickOpen', '>VS Code Azure Functions for Web:');` can be used to open this with a specific prefix... other note, that prefix is quite long...)
  <img width="695" alt="image" src="https://github.com/user-attachments/assets/43a97726-7754-465e-982a-d9f71eb04348">
* Do you really need a Run/Test app? Is the Debugging support in VS Code that hard to find?

### Use Case *

To make it feel a bit less custom, and more aligned with VS Code best practices

**Comment by EvanR-Dev** [comment]
Discussed with the vscode.dev team - we will continue to receive feedback on this during our public preview phase from users. It was mentioned that Tree Views are mainly for displaying data and not for interactions. However, there isn't really a mechanism in VS Code yet to expose such buttons. For example, there is a way to run but we wouldn't know where else to put a button for Deploy All

We will revisit this - for now we have decided to make all the buttons on one layer (Functions folder will be removed). We may also add new buttons/commands to the view as well which further justifies having this view as it is - but we will likely revisit this after some time

**Comment by TylerLeonhardt** [comment]
> However, there isn't really a mechanism in VS Code yet to expose such buttons

There is. Welcome Views provide this:
https://code.visualstudio.com/api/ux-guidelines/views#welcome-views

**Comment by bamurtaugh** [comment]
> We will revisit this

Since the plan is to revisit, @EvanR-Dev maybe we keep this issue open for tracking over time?
