### ISSUE TITLE
[Bug]: VS Code not showing GitHub connection -- please reopen

### ISSUE THREAD

**Issue by nirmash** [Azure/azure-functions-vscode-web#46]
### Function app name

https://llt2.azurewebsites.net

### Expected Behavior *

I created a function, a local repository and pushed to Github as well as published to Azure. I expect the Source Control pane on Limelight to not show "Initialized repository" button.

### Actual Behavior *

When I opened Limelight I saw the "Initialized repository" and "Publish to Github" buttons in the Source Control pane even though the repository exists in GitHub

### Steps to Reproduce

Create a new flex consumption function app
Open Limelight 
Walk through the tutorial 
Publish the function 
Push the code to Github
Close Limelight 
Open the function app in the Portal 
Open Limelight 
Wait to load 
Click the Source Control icon 
Pane shows up with "Initialized repository" and "Publish to Github"  buttons

### Priority

Low (happening rarely)

**Comment by nirmash** [comment]
I was able to repro a few times

**Comment by YunchuWang** [comment]
unable to repro myself

![Image](https://github.com/user-attachments/assets/9f47630d-7596-44f9-8a4d-a0aec550d738)

**Comment by YunchuWang** [comment]
both insiders/prod vscode, unable to repro

![Image](https://github.com/user-attachments/assets/7fcbc58d-fc47-465c-aa73-66d553f33216)

**Comment by nirmash** [comment]
![2024-08-23 09 22 49](https://github.com/user-attachments/assets/a9a74f7e-75dd-4982-9c96-9849eb4f0ad0)
Still broken for me on a brand new function, https://ll2.azurewebsites.net. Can I help debug?
