### ISSUE TITLE
Save project code walkthrough step is no-op when choosing to download a file locally.

### ISSUE THREAD

**Issue by bhavyaus** [Azure/azure-functions-vscode-web#47]
The action shown in the screenshot does not download a copy.

![Image](https://github.com/user-attachments/assets/10273887-cbf9-40bb-8358-798286e09f79)

**Comment by EvanR-Dev** [comment]
Hi, do you see a message whenever you click on Download a copy? @bhavyaus

**Comment by EvanR-Dev** [comment]
Have added clearer instructions for this:
![image](https://github.com/user-attachments/assets/87f81eeb-24c6-4d54-a850-9d6febfcd034)
