### ISSUE TITLE
[Bug]: Don't display recent environments on reconnect

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-functions-vscode-web#48]
### Function app name

glengatest-flex-py

### Expected Behavior *

After I reconnect and see a link under **Recent** I would think that this would get me back to my environment.   

### Actual Behavior *

Since it's a link to an old environment it just kind of blows up the page. We shouldn't even show these recent envs in the **Recent** list.

### Steps to Reproduce

1. Create an env from the portal and work past the timeout.
2. Refresh the page to get a new session and click a previous session in the **Recent** list. 

<img width="509" alt="image" src="https://github.com/user-attachments/assets/4b0f8de7-1f96-443f-9f6e-e0a3a5764405">

### Priority

Medium (intermittent)

**Comment by EvanR-Dev** [comment]
There is a workbench option that will disable this - added, to be included in next ext release

**Comment by EvanR-Dev** [comment]
Need to reopen because apparently every walkthrough has a "back" button that will get you back to this screen - has to be a VS Code change
