### ISSUE TITLE
Add .gitignore on function app initialization

### ISSUE THREAD

**Issue by eamonoreilly** [Azure/azure-functions-vscode-web#5]
### Feature Name *

Add .gitignore file so that when project is git initialized, only the function app files are included

### Feature Description *

We could add a .gitignore like https://github.com/Azure/azure-functions-openai-extension/blob/main/.gitignore to the project initialization so we only include Azure Functions files and excludes local.settings.json

### Use Case *

When you go to initialize the folder with Git in VSCode, it will include all files created in the folder without the .gitignore file.

### Benefits

Prevents bringing in unwanted files under source control

**Comment by EvanR-Dev** [comment]
Closing in favor of #42
