### ISSUE TITLE
[Bug]: I did not discover the cold start load status in bottom-right of screen

### ISSUE THREAD

**Issue by paulyuk** [Azure/azure-functions-vscode-web#50]
### Expected Behavior *

I would have expected a discoverable loading status in the top right or center of the screen, more like CodeSpaces.  I like how code spaces shows you a loading screen until the real editor is ready.

### Actual Behavior *

@vrdmr @nirmash what I also notice are the visual cues, which confused me:
- the first phase is setting up dev tunnels, but my eyes were trained to look at that empty patience bar on the Extensions window, when the real status (which was fine) was down in the bottom left notification area.  I wish all the notifications could be top left, but if not, maybe we tell the user to look bottom right somehow?

- then the extensions light up and install

- then the terminal appears

- but then i see start page.  Why not the create?  

For clarity i will make this a new issue.

### Priority

Low (happening rarely)

**Comment by EvanR-Dev** [comment]
VS Code exts do not natively support toasts/notifications that are centered on the screen. In the future, we can explore a splash screen that would need to be done with the Portal team. Codespaces uses a React app
