### ISSUE TITLE
[Bug]: new Python function creates but does not run with error "Could not find the task 'func: host start'"

### ISSUE THREAD

**Issue by paulyuk** [Azure/azure-functions-vscode-web#52]
### Function app name

limelight3-portalpython
EastUS2
"homeStamp": "waws-prod-bn1-153"

### Tunnel ID (if available)

joyful-cat-2ddp719.use2

### Expected Behavior *

New function can F5 and run with no errors

### Actual Behavior *

First error:
`Could not find the task 'func: host start'.`
[Debug anyway]|[Cancel]|[Configure task]

After clicking `Debug Anyway` I see..

Second error:
`Couldn't find a debug adapter descriptor for debug type 'debugpy' (extension might have failed to activate)`
[Open 'launch.json']|[Cancel]

### Additional Information

Manual `func start` from terminal is ok, but that's for power users.

I was curious if the Azure Functions vscode extension was not loaded but it looks good:

![image](https://github.com/user-attachments/assets/2a8fbf41-2dc0-4ff0-902f-17973cb48a88)

### Priority

Medium (intermittent)

**Comment by EvanR-Dev** [comment]
@paulyuk - is it possible that the Python VS Code ext didn't get installed here? I can't reproduce this. Hitting F5 for me is the same as doing run/test - runs and can debug as normal

**Comment by EvanR-Dev** [comment]
Discussed offline - Python ext wasn't installed at the time
