### ISSUE TITLE
[Bug]: Feedback URL needs signin - prevent that

### ISSUE THREAD

**Issue by vrdmr** [Azure/azure-functions-vscode-web#54]
### Expected Behavior *

The URL should be https://github.com/Azure/azure-functions-vscode-web/issues/ and not https://github.com/Azure/azure-functions-vscode-web/issues/new/choose
<img width="1187" alt="image" src="https://github.com/user-attachments/assets/358de85f-4e39-48ab-abd6-d778b047891b">

### Priority

Low (happening rarely)

**Comment by EvanR-Dev** [comment]
Released
