### ISSUE TITLE
[Bug]: When creating node func and discarding - an error pops up

### ISSUE THREAD

**Issue by vrdmr** [Azure/azure-functions-vscode-web#55]
### Function app name

<img width="1029" alt="image" src="https://github.com/user-attachments/assets/777697af-32bd-4232-972e-366404572c35">

### Steps to Reproduce

1. Click Create
<img width="468" alt="image" src="https://github.com/user-attachments/assets/93407ba4-877b-44eb-b732-1fadd40f2578">
2. Hit escape button when this pops up 
<img width="585" alt="image" src="https://github.com/user-attachments/assets/88cd2616-5453-40c6-8656-63cfcf45c754">
3. The error shows up
<img width="953" alt="image" src="https://github.com/user-attachments/assets/167a3ccd-62b9-4c82-84b6-4b0e0aebd390">

### Priority

Low (happening rarely)

**Comment by EvanR-Dev** [comment]
Released
