### ISSUE TITLE
[Bug]: Missing capitalization in Azure Portal entrypoint

### ISSUE THREAD

**Issue by bamurtaugh** [Azure/azure-functions-vscode-web#6]
### Expected Behavior *

This should be `Open in VS Code for the Web` (with a capital C for Code):

![Image](https://github.com/user-attachments/assets/e62e39af-cef0-4c2b-987b-a40f6740a95b)

### Actual Behavior *

Lowercase `code` today.

### Priority

Low (happening rarely)

**Comment by shimedh** [comment]
https://msazure.visualstudio.com/One/_git/AAPT-Antares-AntUX/pullrequest/10705616

**Comment by EvanR-Dev** [comment]
Released
