### ISSUE TITLE
Azurite blob service does not start automatically when debugging

### ISSUE THREAD

**Issue by eamonoreilly** [Azure/azure-functions-vscode-web#64]
### Function app name

N/A

### Expected Behavior *

When you click on Run / Test function, we should start the Azurite blob service automatically if it is not running

### Actual Behavior *

Function will hang for a while trying to reach blob storage service (If using "AzureWebJobsStorage": "UseDevelopmentStorage=true") that is the default

![image](https://github.com/user-attachments/assets/a50d9f14-a03e-4148-bf0b-1c34ca091571)

![image](https://github.com/user-attachments/assets/5c308128-8563-4944-8302-34df7ea8a1d6)

### Steps to Reproduce

1. Make sure that blob service in Azurite is not running
2. Click on Run/Test function

The above error will happen. If you manually start the blob service in VSCode, the error will not happen when run again.

### Priority

Low (happening rarely)

**Comment by ggailey777** [comment]
This is particularly annoying because if you actually start Azurite ahead of time you get a bunch of "azurite already running" warnings 😦

**Comment by EvanR-Dev** [comment]
Closing in favor of #11
