### ISSUE TITLE
[Bug]: We should enable the right click menu on functions in the Run/Test function

### ISSUE THREAD

**Issue by eamonoreilly** [Azure/azure-functions-vscode-web#65]
### Expected Behavior *

We should add the right click menu to the functions so they can be executed easily (particularity for non http functions). This menu exists in the VS Code functions extension so could probably be reused. I don't think we need the disable or add binding items.
![image](https://github.com/user-attachments/assets/f009c370-8b94-476e-b0e3-05e59ad25411)

### Actual Behavior *

There is no easy way to run non http trigger functions from within VS Code.

### Steps to Reproduce

1. Click on Run/Test function to start debugging
2. Right click on the functions listed - there is no Execute Function 

### Priority

Low (happening rarely)

**Comment by vrdmr** [comment]
Done and released.

>  This menu exists in the VS Code functions extension so could probably be reused. I don't think we need the disable or add binding items.

Now - clicking the function name executes the function and hovering over the name shows the available action.
