### ISSUE TITLE
[Bug]: Make workspace (local) more prominent

### ISSUE THREAD

**Issue by ejizba** [Azure/azure-functions-vscode-web#67]
### Expected Behavior *

It seems like the "Workspace (Local)" view is an important part of limelight, but I never would've opened it if I wasn't explicitly looking for it (because I heard about it from the team).

Here it was collapsed by default for me:

<img width="586" alt="Screenshot 2024-09-13 at 3 37 04 PM" src="https://github.com/user-attachments/assets/60db919a-edd0-416c-bc15-821df98f99d0">

In addition, the name "Workspace" doesn't really mean anything to me. If I have a workspace open, _everything_ in the UI is related to the workspace in some way.

### Actual Behavior *

First, would be nice if it was open/expanded by default.

For the name, I feel it should reference Azure, Functions, or VS Code for the Web. You could even combine all three and say "Azure Functions in VS Code for the Web". It's a bit long, but it does tie in nicely with the entry point in the portal (aka "Open in VS Code for the Web").

**Comment by EvanR-Dev** [comment]
Renamed
