### ISSUE TITLE
Long cold start

### ISSUE THREAD

**Issue by bamurtaugh** [Azure/azure-functions-vscode-web#7]
Connecting to vscode.dev took about 90 seconds - I think this is much longer than expected?

**Comment by EvanR-Dev** [comment]
I have just added our latest image to the precache in all regions. There will be further precaching done that will release on Monday with all the other Functions images - this should help with coldstart. There is further work being with using placeholders to further optimize that will be released later

**Comment by EvanR-Dev** [comment]
Closing in favor of #19
