### ISSUE TITLE
Need to reload after initial connection

### ISSUE THREAD

**Issue by bamurtaugh** [Azure/azure-functions-vscode-web#8]
Why do I need to Reload Window upon my first connection?

![Image](https://github.com/user-attachments/assets/caf87c49-6858-4b68-9fa2-840d6875db4a)

**Comment by bamurtaugh** [comment]
I did reload, and it took ~35 seconds to reconnect, which feels non-ideal (I already waited 90 seconds for initial connect https://github.com/Azure/azure-functions-vscode-web/issues/7, so I'm 2 mins+ for initial start time).

**Comment by EvanR-Dev** [comment]
This is something we're aware of - essentially the container has the extensions at the time it was built - so extensions that get updated after that build and release will show that. We will be more proactively releasing our image to avoid this. We also can look into doing a forced refresh of that extension without letting the browser refresh if we track the versions between the image and the client (VS Code client has control over extension installations as well)

**Comment by EvanR-Dev** [comment]
There is a vscode setting that prevents auto-updating of exts. This or releasing frequently addresses the issue. Leaning towards faster releases as having the latest version is quite important
