### ISSUE TITLE
No files in Explorer

### ISSUE THREAD

**Issue by bamurtaugh** [Azure/azure-functions-vscode-web#9]
After connecting to my vscode.dev instance, the Explorer opened by default for me, but with no files, so I wondered if I actually wasn't connected properly:

![Image](https://github.com/user-attachments/assets/7c85720e-8aed-48bc-b977-cafb7e9e0fdf)

If this is expected at this point, I would've loved a button like `Create a Function App`. Though I suppose that's maybe covered by the getting started walkthrough that opened, so perhaps this issue is already addressed 😄 still just wanted to report as it was my first impression.

**Comment by EvanR-Dev** [comment]
The walkthrough does address this - but also as you see the "Workspace (Local)" is a separate extension that will provide this. If your app is undeployed, then the walkthrough acts in place to help get started

**Comment by EvanR-Dev** [comment]
Closing as this is the expected behavior - undeployed apps are empty and the walkthrough is intended to be used as the getting started experience
